language: php
php:
  - 7.1.9
services:
  - docker
before_install:
  # Upgrade docker/docker-compose
  - docker -v
  - cp .env.example .env
  # Build and create our containers
  - docker login -u="$adegbenga.adeye@outlook.com" -p="$SWATCH@1602"
  - docker-compose up -d
  - docker ps -a
notifications:
  slack:
    rooms:
	  - erpfreeproject:4s5EzjbwL75fpAF1HV9kNvYh#deployments
	  - erpfreeproject:4s5EzjbwL75fpAF1HV9kNvYh#erp
