runtime: php
env: flex

runtime_config:
    document_root: public
    front_controller_file: index.php
    enable_stackdriver_integration: true

env_variables:
    # Put production environment variables here.
    APP_LOG: errorlog
    APP_ENV: staging
    APP_DEBUG: true
    APP_KEY: base64:9ymmOm8LPqrXOokuC0QEwa5zrUB3SnDOgXgDeuGiU0s=
    STORAGE_DIR: /tmp

    LOG_CHANNEL: stackdriver

    ## SendGrid Details
    # SENDGRID_APIKEY: your-sendgrid-api-key
    # SENDGRID_SENDER: your-sendgrid-sender

    ## Set these environment variables according to your CloudSQL configuration.
    DB_HOST: 127.0.0.1
    DB_PORT: 5432
    DB_CONNECTION: system
    DB_DATABASE: saas-erp-db
    DB_USERNAME: saaserp_user
    DB_PASSWORD: 5d8unGqc021wwpeE
    DB_SOCKET: "/cloudsql/saas-erp-246508:europe-west6:saas-erp-db"
    #  POSTGRES_USER: USER
    # POSTGRES_PASSWORD: PASSWORD
    # POSTGRES_DSN: pgsql:dbname=DATABASE;host=/cloudsql/CONNECTION_NAME

beta_settings:
    cloud_sql_instances: "saas-erp-246508:europe-west6:saas-erp-db"

# Ensure we skip ".env", which is only for local development
skip_files:
    - .env
    - .git
