version: "3.7"
services:
  #App service PHP 7.1.27
  app:
    build: docker/php
    depends_on:
      - db
    container_name: app
    restart: unless-stopped
    working_dir: /application
    volumes:
      - .:/application
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:1.16.0
    depends_on:
      - app
    container_name: webserver
    restart: unless-stopped
    tty: true
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network

  #Postgres Service
  db:
    build: docker/postgres
    container_name: "db"
    restart: always
    ports:
      - "32768:5432"
    environment:
      - POSTGRES_MULTIPLE_DATABASES=erp,erp_testing
      - POSTGRES_USER=docker_erp_user
      - POSTGRES_PASSWORD=docker_erp_password
    volumes:
      - my_dbdata:/var/lib/postgresql/
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  my_dbdata:
    driver: local
