version: 2
jobs:
  build:
    working_directory: /var/www/html
    docker:
      - image: php:7.1.27-apache
        environment:
          APP_ENV: test
      - image: postgres:latest
        environment:
          - POSTGRES_DB: erp
          - POSTGRES_USER: docker_erp_user
          - POSTGRES_PASSWORD: docker_erp_password
    parallelism: 4
    steps:
      - checkout
      - run:
          name: Install System Packages
          command: apt-get update && apt-get install -y git unzip zlib1g-dev libpq-dev
      - run:
          name: Install PHP Extensions
          command: docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql && docker-php-ext-install pdo pdo_pgsql zip
      - run:
          name: Install Composer
          command: |
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            php -r "copy('https://composer.github.io/installer.sig', 'composer-setup.sig');"
            php -r "if (hash_file('SHA384', 'composer-setup.php') === trim(file_get_contents('composer-setup.sig'))) { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
            php composer-setup.php
            php -r "unlink('composer-setup.php');"
      - run:
          name: Setup Laravel testing environment variables for CircleCI test
          command: cp .env.testing .env
      - run:
          name: Display PHP information
          command: |
            php -v
            php composer.phar --version
      - run:
          name: Install project dependencies
          command: php composer.phar install
      - run:
          name: Install Lumen
          command: php composer.phar global require "laravel/lumen-installer"
      - run:
          name: Make Artisan executable
          command: chmod +x artisan && ls && pwd #php /root/.composer/vendor/bin/lumen list
      - run:
          name: Execute the artisan command
          command: php artisan list
      # - run:
      #     name: Migrate Laravel Database
      #     command: php /var/www/html/artisan migrate:fresh --seed --env=testing
      # - run:
      #     name: Run Docker
      #     command: docker-compose up -d
      - run:
          name: Run Tests
          command: php phpunit #vendor/bin/phpunit
workflows:
  version: 2
  workflow:
    jobs:
      - build
