version: 2
jobs:
  build:
    working_directory: /var/www/html
    docker:
      - image: php:7.2.19-apache
      - image: postgres:latest
        environment:
          - POSTGRES_DB: erp
          - POSTGRES_USER: docker_erp_user
          - POSTGRES_PASSWORD: docker_erp_password
    parallelism: 4
    steps:
      - checkout
      - run:
          name: Install System Packages
          command: apt-get update && apt-get install -y git unzip zlib1g-dev libpq-dev
      - run:
          name: Install PHP Extensions
          command: docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql && docker-php-ext-install pdo pdo_pgsql zip
      - run:
          name: Install Composer
          command: |
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            php -r "copy('https://composer.github.io/installer.sig', 'composer-setup.sig');"
            php -r "if (hash_file('SHA384', 'composer-setup.php') === trim(file_get_contents('composer-setup.sig'))) { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
            php composer-setup.php
            php -r "unlink('composer-setup.php');"
      - run:
          name: Install project dependencies
          command: php composer.phar require --dev phpunit/php-invoker
      - run:
          name: Run CodeSniffer
          command: php vendor/bin/phpcs --extensions=php --standard=ruleset.xml application
      - run:
          name: Run Tests
          command: php vendor/bin/phpunit
      - add_ssh_keys:
          fingerprints:
            - "41:df:a1:e9:40:ac:f4:9b:47:0a:ee:a1:98:01:7c:38"
      - run:
          name: Deploy to Google Cloud Platform
          command: |
            if [ "$CIRCLE_BRANCH" == 'master' ]; then
              ssh -o "StrictHostKeyChecking no" $USER@$IPADDRESS 'cd /home/andelatsm/erp && sudo docker system prune -f --volumes && sudo docker network prune -f && git pull https://github.com/deye9/erp.git && composer install && sudo docker-compose down && sudo docker-compose build --no-cache && sudo docker-compose up -d'
            fi
      # sudo /etc/init.d/apache2 stop
      # - run:
      #     name: Migrate Laravel Database
      #     command: php artisan migrate:fresh --seed --env=testing

workflows:
  version: 2
  workflow:
    jobs:
      - build
